language: android
os: linux
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - android-29

before_script:
  - java -version
  - go version

script:
  - ./gradlew :tagIfNeeded
  - ./gradlew :ziti:check :ziti:assemble
  - ./gradlew :ziti-android:check :ziti-android:assemble

after_success:
  - git push --tags