version: "~> 1.0"

language: java
os: linux
dist: bionic

env:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

before_install:
  - wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip -O /tmp/android-sdk.zip
  - mkdir $HOME/android_sdk
  - unzip /tmp/android-sdk.zip -d $HOME/android_sdk
  - yes | $HOME/android_sdk/tools/bin/sdkmanager --sdk_root=$HOME/android_sdk --licenses
  - $HOME/android_sdk/tools/bin/sdkmanager --sdk_root=$HOME/android_sdk --list
  - echo $JAVA_HOME
  - yes | sdkmanager "platforms;android-29"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo ${gh_ci_key} | base64 --decode > github_deploy_key
  - chmod 600 github_deploy_key
  - git config user.name ziti-ci
  - git config user.email ziti-ci@netfoundry.io
  - git config core.sshCommand 'ssh -i github_deploy_key'
  - git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}

stages:
  - name: test and build

  - name: tag and publish
    if: branch = master and type != pull_request

jobs:
  include:

    - stage: test and build

      script:
        - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
        - ./gradlew build
        - ./gradlew :ziti:check
        - ./gradlew :ziti-android:check

    - stage: tag and publish
      script:
        - ./gradlew :tagIfNeeded
        - ./gradlew assemble :ziti:artifactoryPublish :ziti-android:artifactoryPublish
        - git push --tags --verbose
