version: "~> 1.0"

language: android
os: linux
dist: trusty

env:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

android:
  components:
    - build-tools-29.0.3
    - android-29
  licenses:
    - etc/android-sdk-license
    - etc/android-sdk-preview-license

before_install:
  - yes | sdkmanager "platforms;android-29"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo ${gh_ci_key} | base64 --decode > github_deploy_key
  - chmod 600 github_deploy_key
  - git config user.name ziti-ci
  - git config user.email ziti-ci@netfoundry.io
  - git config core.sshCommand 'ssh -i github_deploy_key'
  - git remote set-url origin git@github.com:${TRAVIS_REPO_SLUG}

stages:
  - name: tagging
    if: branch = master

  - name: test and build

  - name: publish
    if: branch = master and type != pull_request

jobs:
  include:
    - stage: tagging
      script:
        - ./gradlew :tagIfNeeded

    - stage: test and build
      script:
        - ./gradlew :ziti:check :ziti:assemble
        - ./gradlew :ziti-android:check :ziti-android:assemble

    - stage: publish
      script:
        - ./gradlew :ziti:artifactoryPublish :ziti-android:artifactoryPublish
        - git push --tags --verbose
