name: CI build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.GITHUB_RUN_NUMBER }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: Check
        run: ./gradlew check
      - name: Build
        run: ./gradlew build assemble