name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.GITHUB_RUN_NUMBER }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Show Info
        run: ./gradlew :showInfo
      - name: Build with Gradle
        run: ./gradlew build assemble
      - name: Publish to Bintray
        env:
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayKey: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew bintrayUpload -Dbintray.user=${bintrayUser} -Dbintray.key=${bintrayKey}

